### ISSUE TITLE
[framework] implementation

### ISSUE THREAD

**Issue by brueggemann** [SovereignCloudStack/rookify#1]
Implement a framework called `rookify` with all the the nice features.

- [x] A repo in https://github.com/SovereignCloudStack needs to be created
  - a PR like https://github.com/SovereignCloudStack/github-manager/pull/225/files needs to be created to get this integrated into [github-manager](https://github.com/SovereignCloudStack/github-manager)

**Comment by NotTheEvilOne** [comment]
With #67 I would define all basic framework implementation to be completed. I'll close this issue therefore.
