### ISSUE TITLE
[module] CRDs CephFileSystem

### ISSUE THREAD

**Issue by yeoldegrove** [SovereignCloudStack/rookify#11]

**Comment by NotTheEvilOne** [comment]
A closer look at [Rook's crds.yaml](https://github.com/rook/rook/blob/master/deploy/examples/crds.yaml) shows that a name can not be given for `cephfs_metadata`. Further analysis at the [code level](https://github.com/rook/rook/blob/643986224e60e60bbec33f887665a106d0736a51/pkg/operator/ceph/file/filesystem.go#L171) revealed that metadata pool names are semi-hardcoded with a given suffix at the time of writing.

A similar approach must be implemented like for [data pools](https://github.com/rook/rook/blob/643986224e60e60bbec33f887665a106d0736a51/pkg/operator/ceph/file/filesystem.go#L300) before migration can be supported without forcing a specific naming scheme.
