### ISSUE TITLE
[framework] states

### ISSUE THREAD

**Issue by yeoldegrove** [SovereignCloudStack/rookify#3]
What happens if a migration fails? Is there a way to resume migrations?

**Comment by NotTheEvilOne** [comment]
This is usually implemented by a state machine. I'll investigate for some options with the following feature set:
- Has dependency tree
- Has at least key/value store
- Can handle conditional dependencies (could be implemented by skipping if a condition is not met)
- Can store and load data from local storage

**Comment by NotTheEvilOne** [comment]
Here's a [research document](https://input.scs.community/xYe5raJMRGSrndwNG7S5_g) for yesterdays comment about library feature investigation.

**Comment by NotTheEvilOne** [comment]
This issue will be closed by the linked PR. The background for this issue showed to be more complex than initially described.

What are states used for?
"rookify" contains logic to first validate and verify (`preflight` state) existing configuration and later applies or executes it (`execution` state). If an error occurs (hopefully meaningful) exceptions are thrown.

The initial code contained a self backed logic to load modules and executes them in order. As this code had some design issues we analyzed alternatives using an external library.

Unfortunately that not only means that the loading and execution logic needs to be rewritten but all modules up to date need to be changed. At the time of writing the PR contains `transitions` as the selected external library to run module logic in the correct order for both states. Furthermore result data are stored persistently if configured.
