### ISSUE TITLE
[docs] migration

### ISSUE THREAD

**Issue by yeoldegrove** [SovereignCloudStack/rookify#5]
Document the following:
  - [ ] migration requirements
  - [ ] migration preparations
  - [ ] migration
  - [ ] rollback

**Comment by artificial-intelligence** [comment]
might be worthwhile to also document these settings?

https://github.com/SovereignCloudStack/rookify/blob/main/config.example.yaml

**Comment by boekhorstb1** [comment]
udpated README [here](https://github.com/SovereignCloudStack/rookify/pull/72)

**Comment by boekhorstb1** [comment]
started with docs here:

```
https://github.com/SovereignCloudStack/rookify/pull/72https://github.com/SovereignCloudStack/rookify/pull/72
```

**Comment by NotTheEvilOne** [comment]
Issue in the OSISM repository is ready to be merged. Let's close this one in favor of the OSISM one.
