### ISSUE TITLE
Add support to display current pickle state file and content

### ISSUE THREAD

**Issue by NotTheEvilOne** [SovereignCloudStack/rookify#60]
To verify the identified and prepared data for migration of each "rookify" module a new method may be implemented for each module to present it's own data if "rookify" is called with a command line argument.

- Output may be limited to states previously executed successfully.
- Module iteration should not follow the module dependencies but be alphabetical for easier readability.
- Presentation should focus on `preflight` states but may also show information if flags like `migrated` is set at the `execution` state

**Comment by boekhorstb1** [comment]
ok I started here: https://github.com/SovereignCloudStack/rookify/tree/prs/adding-pickle-output-to-cli
