### ISSUE TITLE
Rookify should react on  Ctrl C (SIGINT, interrupt signal)

### ISSUE THREAD

**Issue by boekhorstb1** [SovereignCloudStack/rookify#89]
I think it would be good if rookify would be "interruptable" with SIGINT

**Comment by NotTheEvilOne** [comment]
AFAIK the Python code reacts on `SIGINT` the way a user would expect it. If the code is waiting for responses of `librados` you might see different behavior. Could you share some more insight where it does not react on SIGINT?

**Comment by boekhorstb1** [comment]
ok, when it is in the process of lets say "migrating a mon", or something else, then I cannot discontinue the process with ctrl -c. I can only use ctrl -z to stop the process. But maybe this is intended.

**Comment by NotTheEvilOne** [comment]
C code can't be stopped at all times unfortunately.
