### ISSUE TITLE
[tests] testbed migration

### ISSUE THREAD

**Issue by yeoldegrove** [SovereignCloudStack/rookify#9]

**Comment by NotTheEvilOne** [comment]
Let's extend and precise this issue to reflect current features additionally available:
- Test OSISM testbed [1] with defaults
- Test OSISM testbed with Debian
- Test OSISM testbed with CentOS

[1] https://github.com/osism/testbed

**Comment by NotTheEvilOne** [comment]
Testing of testbed has been completed currently.
